### PR TITLE
RoomListDock: remember state of groups

### LINKED ISSUE #499: Remember expanded/collapsed state of groups in the room list
The code is there but doesn't work for some reason, so it's a bug rather than a feature.

### PR DESCRIPTION
**Pull request by krkk**
Closes #499

### CODE REVIEW

File: client/roomlistdock.cpp [hunk 1]
```diff
@@ -155,7 +155,10 @@ RoomListDock::RoomListDock(MainWindow* parent)
         }
     });
     connect( model, &RoomListModel::groupAdded, this, [this] (int pos) {
-        view->expand(model->index(pos, 0));
+        QMatrixClient::SettingsGroup sg { QStringLiteral("UI/RoomsDock") };
+        QString group = model->roomGroupAt(model->index(pos, 0)).toString();
```
Comment (KitsuneRal) [inline client/roomlistdock.cpp]:
```suggestion
        const auto group = model->roomGroupAt(model->index(pos, 0)).toString();
```
