### PR TITLE
UserListModel: fix search crash

### LINKED ISSUE #521: Attempting to search users when not in a room results in a crash
### Steps to reproduce

- Open Quaternion
- Type a letter into user search field

Crash

Quaternion dumps logs to the standard output. If you can find the logs and
identify any log snippets relevant to your issue, please include
those here (please be careful to remove any personal or private data):

```
Process:               quaternion [67474]
Path:                  /Applications/quaternion.app/Contents/MacOS/quaternion
Identifier:            com.github.quaternion
Version:               0.0.9.4 (0.0.9.4)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           quaternion [67474]
User ID:               501

Date/Time:             2019-03-03 09:28:47.223 -0600
OS Version:            Mac OS X 10.14.3 (18D109)
Report Version:        12
Anonymous UUID:        D2B10E1C-FCC1-D778-1131-4967D5F83A7D

Sleep/Wake UUID:       AA61EAF1-4F54-4ABA-B35D-54B70ECB342D

Time Awake Since Boot: 1000000 seconds
Time Since Wake:       4000 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000010
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [67474]

VM Regions Near 0x10:
--> 
    __TEXT                 000000010c222000-000000010c354000 [ 1224K] r-x/rwx SM=COW  /Applications/quaternion.app/Contents/MacOS/quaternion

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.github.quaternion         	0x000000010c2a7bc9 QMatrixClient::Room::users() const + 9
1   com.github.quaternion         	0x000000010c26ce67 UserListModel::filter(QString const&) + 87
2   org.qt-project.QtCore         	0x000000010da85e42 QMetaObject::activate(QObject*, int, int, void**) + 1474
3   org.qt-project.QtWidgets      	0x000000010c53bc47 QLineEdit::textEdited(QString const&) + 55
4   org.qt-project.QtWidgets      	0x000000010c532d52 0x10c3e5000 + 1367378
5   org.qt-project.QtCore         	0x000000010da8619e QMetaObject::activate(QObject*, int, int, void**) + 2334
6   org.qt-project.QtWidgets      	0x000000010c53d086 QWidgetLineControl::finishChange(int, bool, bool) + 550
7   org.qt-project.QtWidgets      	0x000000010c541a59 QWidgetLineControl::processKeyEvent(QKeyEvent*) + 1097
8   org.qt-project.QtWidgets      	0x000000010c538352 QLineEdit::keyPressEvent(QKeyEvent*) + 34
9   org.qt-project.QtWidgets      	0x000000010c42f512 QWidget::event(QEvent*) + 530
10  org.qt-project.QtWidgets      	0x000000010c537699 QLineEdit::event(QEvent*) + 745
11  org.qt-project.QtWidgets      	0x000000010c3f546d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
12  org.qt-project.QtWidgets      	0x000000010c3f69de QApplication::notify(QObject*, QEvent*) + 910
13  org.qt-project.QtCore         	0x000000010da54f64 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
14  org.qt-project.QtWidgets      	0x000000010c44efc1 0x10c3e5000 + 434113
15  org.qt-project.QtWidgets      	0x000000010c44e391 0x10c3e5000 + 430993
16  org.qt-project.QtWidgets      	0x000000010c3f546d QApplicationPrivate::notify_helper(QObject*, QEvent*) + 269
17  org.qt-project.QtWidgets      	0x000000010c3f6897 QApplication::notify(QObject*, QEvent*) + 583
18  org.qt-project.QtCore         	0x000000010da54f64 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 164
19  org.qt-project.QtGui          	0x000000010d37160c QGuiApplicationPrivate::processKeyEvent(QWindowSystemInterfacePrivate::KeyEvent*) + 156
20  org.qt-project.QtGui          	0x000000010d35813b QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 219
21  org.qt-project.QtGui          	0x000000010d353357 QWindowSystemInterface::flushWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 599
22  libqcocoa.dylib               	0x000000010f97d0d4 0x10f959000 + 147668
23  libqcocoa.dylib               	0x000000010f97d298 0x10f959000 + 148120
24  com.apple.AppKit              	0x00007fff48a86436 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 6946
25  com.apple.AppKit              	0x00007fff48a846c9 -[NSWindow(NSEventRouting) sendEvent:] + 481
26  libqcocoa.dylib               	0x000000010f981842 0x10f959000 + 165954
27  com.apple.AppKit              	0x00007fff4892230b -[NSApplication(NSEvent) sendEvent:] + 2823
28  libqcocoa.dylib               	0x000000010f987cba 0x10f959000 + 191674
29  com.apple.AppKit              	0x00007fff4890f19d -[NSApplication run] + 755
30  libqcocoa.dylib               	0x000000010f9845bf 0x10f959000 + 177599
31  org.qt-project.QtCore         	0x000000010da503de QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 430
32  org.qt-project.QtCore         	0x000000010da55552 QCoreApplication::exec() + 130
33  com.github.quaternion         	0x000000010c27ca91 main + 3953
34  libdyld.dylib                 	0x00007fff786bced9 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff788af3f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 2:: Qt bearer thread
0   libsystem_kernel.dylib        	0x00007fff787fe2ee poll + 10
1   org.qt-project.QtCore         	0x000000010daa91ba qt_safe_poll(pollfd*, unsigned int, timespec const*) + 90
2   org.qt-project.QtCore         	0x000000010daaac29 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 873
3   org.qt-project.QtCore         	0x000000010da503de QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 430
4   org.qt-project.QtCore         	0x000000010d89416c QThread::exec() + 140
5   org.qt-project.QtCore         	0x000000010d89d65e 0x10d86f000 + 190046
6   libsystem_pthread.dylib       	0x00007fff788b0305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff788b326f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff788af415 thread_start + 13

Thread 3:: QQmlThread
0   libsystem_kernel.dylib        	0x00007fff787fe2ee poll + 10
1   org.qt-project.QtCore         	0x000000010daa93a0 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 576
2   org.qt-project.QtCore         	0x000000010daaac29 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 873
3   org.qt-project.QtCore         	0x000000010da503de QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 430
4   org.qt-project.QtCore         	0x000000010d89416c QThread::exec() + 140
5   org.qt-project.QtQml          	0x000000010cfb0d09 0x10cd6c000 + 2379017
6   org.qt-project.QtCore         	0x000000010d89d65e 0x10d86f000 + 190046
7   libsystem_pthread.dylib       	0x00007fff788b0305 _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff788b326f _pthread_start + 70
9   libsystem_pthread.dylib       	0x00007fff788af415 thread_start + 13

Thread 4:: QSGRenderThread
0   libsystem_kernel.dylib        	0x00007fff787f97de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff788b3593 _pthread_cond_wait + 724
2   org.qt-project.QtCore         	0x000000010d89ecab 0x10d86f000 + 195755
3   org.qt-project.QtCore         	0x000000010d89ec01 QWaitCondition::wait(QMutex*, unsigned long) + 97
4   org.qt-project.QtQuick        	0x000000010ca54dac 0x10c991000 + 802220
5   org.qt-project.QtQuick        	0x000000010ca54edd 0x10c991000 + 802525
6   org.qt-project.QtQuick        	0x000000010ca55094 0x10c991000 + 802964
7   org.qt-project.QtCore         	0x000000010d89d65e 0x10d86f000 + 190046
8   libsystem_pthread.dylib       	0x00007fff788b0305 _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff788b326f _pthread_start + 70
10  libsystem_pthread.dylib       	0x00007fff788af415 thread_start + 13

Thread 5:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff787f617a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff787f66d0 mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff4b3d3158 __CFRunLoopServiceMachPort + 336
3   com.apple.CoreFoundation      	0x00007fff4b3d26a6 __CFRunLoopRun + 1661
4   com.apple.CoreFoundation      	0x00007fff4b3d1dd6 CFRunLoopRunSpecific + 467
5   com.apple.AppKit              	0x00007fff4891ef89 _NSEventThread + 160
6   libsystem_pthread.dylib       	0x00007fff788b0305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff788b326f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff788af415 thread_start + 13

Thread 6:
0   libsystem_pthread.dylib       	0x00007fff788af3f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff788af3f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff788af3f8 start_wqthread + 0
1   ???                           	0x0000000054485244 0 + 1414025796

Thread 9:: QNetworkAccessManager thread
0   libsystem_kernel.dylib        	0x00007fff787fe2ee poll + 10
1   org.qt-project.QtCore         	0x000000010daa93a0 qt_safe_poll(pollfd*, unsigned int, timespec const*) + 576
2   org.qt-project.QtCore         	0x000000010daaac29 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 873
3   org.qt-project.QtCore         	0x000000010da503de QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 430
4   org.qt-project.QtCore         	0x000000010d89416c QThread::exec() + 140
5   org.qt-project.QtCore         	0x000000010d89d65e 0x10d86f000 + 190046
6   libsystem_pthread.dylib       	0x00007fff788b0305 _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff788b326f _pthread_start + 70
8   libsystem_pthread.dylib       	0x00007fff788af415 thread_start + 13

Thread 10:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff787f97de __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff788b3593 _pthread_cond_wait + 724
2   org.qt-project.QtCore         	0x000000010d89ef38 0x10d86f000 + 196408
3   org.qt-project.QtCore         	0x000000010d89ec8b 0x10d86f000 + 195723
4   org.qt-project.QtCore         	0x000000010d89ec01 QWaitCondition::wait(QMutex*, unsigned long) + 97
5   org.qt-project.QtCore         	0x000000010d8950be 0x10d86f000 + 155838
6   org.qt-project.QtCore         	0x000000010d89d65e 0x10d86f000 + 190046
7   libsystem_pthread.dylib       	0x00007fff788b0305 _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff788b326f _pthread_start + 70
9   libsystem_pthread.dylib       	0x00007fff788af415 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x00000000ffffffff  rbx: 0x00007ffee39dc4b0  rcx: 0x0000000000000000  rdx: 0x0000000000000011
  rdi: 0x00007ffee39dc4b0  rsi: 0x0000000000000000  rbp: 0x00007ffee39dc440  rsp: 0x00007ffee39dc430
   r8: 0x000000000000001d   r9: 0x00000000000007fb  r10: 0x00000000000002e0  r11: 0x0000000000000020
  r12: 0x00007ffee39dc718  r13: 0x00007ffee39dc5e0  r14: 0x00006000029b57e0  r15: 0x00006000029b5920
  rip: 0x000000010c2a7bc9  rfl: 0x0000000000010202  cr2: 0x0000000000000010
  
Logical CPU:     0
Error Code:      0x00000004
Trap Number:     14


Binary Images:
       0x10c222000 -        0x10c353ff7 +com.github.quaternion (0.0.9.4 - 0.0.9.4) <607F1C10-649B-3AB5-AE58-8F7D1AE2B60D> /Applications/quaternion.app/Contents/MacOS/quaternion
       0x10c3e5000 -        0x10c828ff3 +org.qt-project.QtWidgets (5.11 - 5.11.1) <BBDD05ED-151D-3EA8-81E2-221E50E3A62E> /Applications/quaternion.app/Contents/Frameworks/QtWidgets.framework/Versions/5/QtWidgets
       0x10c991000 -        0x10cc63ff3 +org.qt-project.QtQuick (5.11 - 5.11.1) <04F94A65-6825-3311-933A-CDF77BCE4201> /Applications/quaternion.app/Contents/Frameworks/QtQuick.framework/Versions/5/QtQuick
       0x10cd6c000 -        0x10d072fff +org.qt-project.QtQml (5.11 - 5.11.1) <9AB6332E-74E0-3F6A-80F4-FB8791AAAAFE> /Applications/quaternion.app/Contents/Frameworks/QtQml.framework/Versions/5/QtQml
       0x10d112000 -        0x10d118ffb +libqt5keychain.1.dylib (0) <A047AE36-21F6-3C2C-BDD5-3208D3CFD11D> /Applications/quaternion.app/Contents/Frameworks/libqt5keychain.1.dylib
       0x10d127000 -        0x10d19dfff +org.qt-project.QtMultimedia (5.11 - 5.11.1) <1A943D93-7BBF-34F4-AD5B-3DE3FAA390D2> /Applications/quaternion.app/Contents/Frameworks/QtMultimedia.framework/Versions/5/QtMultimedia
       0x10d1ed000 -        0x10d2f3ffb +org.qt-project.QtNetwork (5.11 - 5.11.1) <57397F00-822E-3CDA-8AEC-8AC9A76A54A3> /Applications/quaternion.app/Contents/Frameworks/QtNetwork.framework/Versions/5/QtNetwork
       0x10d33f000 -        0x10d774fef +org.qt-project.QtGui (5.11 - 5.11.1) <1136D8AD-19A9-3CF8-935F-6B2C0023112C> /Applications/quaternion.app/Contents/Frameworks/QtGui.framework/Versions/5/QtGui
       0x10d86f000 -        0x10dd62ff7 +org.qt-project.QtCore (5.11 - 5.11.1) <4F05320A-6BB4-3F3E-898E-2C61ACB9BC56> /Applications/quaternion.app/Contents/Frameworks/QtCore.framework/Versions/5/QtCore
       0x10f959000 -        0x10fab2ff7 +libqcocoa.dylib (0) <2BDF6A75-5683-3E89-8EF2-CECCF3B36EE4> /Applications/quaternion.app/Contents/PlugIns/platforms/libqcocoa.dylib
       0x10faf9000 -        0x10fb23ff3 +org.qt-project.QtPrintSupport (5.11 - 5.11.1) <74244901-C2C0-3A97-A5B1-C1CEBDBD2518> /Applications/quaternion.app/Contents/Frameworks/QtPrintSupport.framework/Versions/5/QtPrintSupport
       0x112aa4000 -        0x112ac8fff +libqmacstyle.dylib (0) <A5F5B6EC-831B-3520-8453-5817E847DB34> /Applications/quaternion.app/Contents/PlugIns/styles/libqmacstyle.dylib
       0x112ad7000 -        0x112adefff +libqgenericbearer.dylib (0) <59D3B534-4BF4-34CB-8ABC-D7FE79E9AEC6> /Applications/quaternion.app/Contents/PlugIns/bearer/libqgenericbearer.dylib
       0x112cfd000 -        0x112d03ff3 +libqgif.dylib (0) <D2EFFA1A-24FB-3480-8222-56EBE231FFE9> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqgif.dylib
       0x112d07000 -        0x112d0efff +libqicns.dylib (0) <A54E5394-46B6-3EE0-A45F-49EFA575DAE1> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqicns.dylib
       0x112d13000 -        0x112d18fff +libqico.dylib (0) <0152F6B2-0F50-3ED5-ACDA-CAC3AE5E2F8C> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqico.dylib
       0x112d1d000 -        0x112d6efff +libqjpeg.dylib (0) <E56A02A1-31DA-3023-8B47-464F8621A470> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqjpeg.dylib
       0x112d74000 -        0x112d78fff +libqmacheif.dylib (0) <70BBCF7D-83B0-3CF5-BFC3-E853F6E12CD8> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqmacheif.dylib
       0x112d7c000 -        0x112d80ffb +libqmacjp2.dylib (0) <CDAB48F2-ADE4-317E-A0D3-7F1C919C8AF6> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqmacjp2.dylib
       0x112d84000 -        0x112d88ffb +libqtga.dylib (0) <E191EBD8-97F0-3BED-91D5-B900269272F4> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqtga.dylib
       0x112d8c000 -        0x112deefff +libqtiff.dylib (0) <2966F012-F908-3958-A204-F957DEDAB03D> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqtiff.dylib
       0x112df6000 -        0x112dfaff3 +libqwbmp.dylib (0) <1173C979-64F7-3B86-80D6-406E907E3A5C> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqwbmp.dylib
       0x112dfe000 -        0x112e8eff7 +libqwebp.dylib (0) <96155711-558C-3B9E-A8DB-6BE060B59DE5> /Applications/quaternion.app/Contents/PlugIns/imageformats/libqwebp.dylib
       0x113a2a000 -        0x113a2dfff +libqtquick2plugin.dylib (0) <106EDDC0-525A-3582-B266-CB12FEE4697B> /Applications/quaternion.app/Contents/PlugIns/quick/libqtquick2plugin.dylib
       0x113a30000 -        0x113a72ffb +libqtquickcontrolsplugin.dylib (0) <F054C2FB-CEB2-3807-978D-0DD30FEC4439> /Applications/quaternion.app/Contents/PlugIns/quick/libqtquickcontrolsplugin.dylib
       0x113a8e000 -        0x113a9fff3 +libqquicklayoutsplugin.dylib (0) <41A84D27-9F1D-3D11-8423-B9888974B726> /Applications/quaternion.app/Contents/PlugIns/quick/libqquicklayoutsplugin.dylib
       0x113ac0000 -        0x113ad8fff +libqtquickcontrols2plugin.dylib (0) <64BFAAA4-3C60-30BF-BD5C-3ACE8D98F818> /Applications/quaternion.app/Contents/PlugIns/quick/libqtquickcontrols2plugin.dylib
       0x113ae7000 -        0x113b77fff +org.qt-project.QtQuickTemplates2 (5.11 - 5.11.1) <ED2B52C8-015E-3063-9C7F-3E0EB9D0CFAD> /Applications/quaternion.app/Contents/Frameworks/QtQuickTemplates2.framework/Versions/5/QtQuickTemplates2
       0x113be6000 -        0x113bfdfff +org.qt-project.QtQuickControls2 (5.11 - 5.11.1) <6D5EF40E-2718-3938-8256-73CB28DFD08C> /Applications/quaternion.app/Contents/Frameworks/QtQuickControls2.framework/Versions/5/QtQuickControls2
       0x113c27000 -        0x113c2afff +libwindowplugin.dylib (0) <1A3516AD-ECAA-3FFE-8AB6-CE4DB3D27D5C> /Applications/quaternion.app/Contents/PlugIns/quick/libwindowplugin.dylib
       0x113c34000 -        0x113c69ff3 +libqtquicktemplates2plugin.dylib (0) <E7F1C288-E769-3E00-BA88-18F0F85F1C5E> /Applications/quaternion.app/Contents/PlugIns/quick/libqtquicktemplates2plugin.dylib
       0x113dae000 -        0x113db1047  libobjc-trampolines.dylib (750.1) <1F602C29-B6EE-34B1-BB43-93A592C1F0BC> /usr/lib/libobjc-trampolines.dylib
       0x113f43000 -        0x113f4aff3 +libqsvgicon.dylib (0) <58ED79F1-DBFF-350B-8FA8-750CE5F8D500> /Applications/quaternion.app/Contents/PlugIns/iconengines/libqsvgicon.dylib
       0x1146d4000 -        0x11479dff7  com.apple.AMDRadeonX4000GLDriver (2.4.10 - 2.0.4) <BD5AEDB7-59B1-3D64-916A-3A8948AF2BA7> /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/AMDRadeonX4000GLDriver
       0x119c44000 -        0x119cc2a87  dyld (655.1) <3EBA447F-A546-366B-B302-8DC3B21A3E30> /usr/lib/dyld
       0x12b0f4000 -        0x12b127ff7 +org.qt-project.QtSvg (5.11 - 5.11.1) <5FE400B3-4252-3047-ADBB-FBC158CC8114> /Applications/quaternion.app/Contents/Frameworks/QtSvg.framework/Versions/5/QtSvg
    0x7fff41036000 -     0x7fff413affff  com.apple.RawCamera.bundle (8.13.0 - 1031.3.2) <C1DB8AE5-1683-3AE8-ACDD-C5EBB3682EE8> /System/Library/CoreServices/RawCamera.bundle/Contents/MacOS/RawCamera
    0x7fff413b2000 -     0x7fff414fdfff  com.apple.AMDMTLBronzeDriver (2.4.10 - 2.0.4) <D06807E4-FC1B-3AE6-AA16-428CE745F924> /System/Library/Extensions/AMDMTLBronzeDriver.bundle/Contents/MacOS/AMDMTLBronzeDriver
    0x7fff414fe000 -     0x7fff41c77fff  ATIRadeonX4000SCLib.dylib (2.4.10) <EF35E927-BE8C-3567-8934-153CA3328250> /System/Library/Extensions/AMDRadeonX4000GLDriver.bundle/Contents/MacOS/ATIRadeonX4000SCLib.dylib
    0x7fff470fc000 -     0x7fff47100fff  com.apple.agl (3.3.2 - AGL-3.3.2) <A65E1BDB-BE14-380C-B283-BB4B79208E7D> /System/Library/Frameworks/AGL.framework/Versions/A/AGL
    0x7fff474cd000 -     0x7fff474cdfff  com.apple.Accelerate (1.11 - Accelerate 1.11) <FC9BE0AB-2371-3ACB-9FD8-A1D439CC4C49> /System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate
    0x7fff474ce000 -     0x7fff474e4ff7  libCGInterfaces.dylib (506.19.1) <9E0F6B86-9E59-3EA9-A586-3A3BA7F2F08A> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/Libraries/libCGInterfaces.dylib
    0x7fff474e5000 -     0x7fff47dd9fcf  com.apple.vImage (8.1 - ???) <D6FBBB13-4760-3811-AF3E-F2B6626B70F6> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vImage.framework/Versions/A/vImage
    0x7fff47dda000 -     0x7fff47f85fcf  libBLAS.dylib (1243.200.4) <432DB967-86BB-3645-8838-CE91CBF51CFA> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
    0x7fff47f86000 -     0x7fff47fcbfff  libBNNS.dylib (38.200.5) <FE0872E1-B992-369F-BD01-2EABBDD318F1> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBNNS.dylib
    0x7fff47fcc000 -     0x7fff48385fff  libLAPACK.dylib (1243.200.4) <670B40E4-AE2F-3311-8ACC-E355F9A36769> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib
    0x7fff48386000 -     0x7fff4839bffb  libLinearAlgebra.dylib (1243.200.4) <4F53BB84-19EB-3B37-ADD7-553077851007> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLinearAlgebra.dylib
    0x7fff4839c000 -     0x7fff483a1ff3  libQuadrature.dylib (3.200.2) <4FBCAC0A-81A4-3C53-8458-27F3569C809D> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libQuadrature.dylib
    0x7fff483a2000 -     0x7fff4841fffb  libSparse.dylib (79.200.5) <2D650C50-E87E-3F24-9BFA-C8EB6DE1A6E9> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparse.dylib
    0x7fff48420000 -     0x7fff48432ffb  libSparseBLAS.dylib (1243.200.4) <16E0C963-955E-3197-9EE0-256A61DB9D57> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libSparseBLAS.dylib
    0x7fff48433000 -     0x7fff485d1fdb  libvDSP.dylib (671.220.1) <95AA3236-5D63-35AF-9305-FDC361365110> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvDSP.dylib
    0x7fff485d2000 -     0x7fff48749ff3  libvMisc.dylib (671.220.1) <6F0164E4-3812-3F1D-AEBC-AF3AFF207FB6> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libvMisc.dylib
    0x7fff4874a000 -     0x7fff4874afff  com.apple.Accelerate.vecLib (3.11 - vecLib 3.11) <0AB4E69A-8159-3BA5-984D-002B5ACB175C> /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/vecLib
    0x7fff488fb000 -     0x7fff4971cffb  com.apple.AppKit (6.9 - 1671.20.108) <D460682F-1B60-372E-A8E5-58D7F3A1CB3A> /System/Library/Frameworks/AppKit.framework/Versions/C/AppKit
    0x7fff4976e000 -     0x7fff4976efff  com.apple.ApplicationServices (50.1 - 50.1) <86D6F10E-21F8-3CDC-9838-EB07A1C54BA9> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices
    0x7fff4976f000 -     0x7fff497daff7  com.apple.ApplicationServices.ATS (377 - 453.11) <4080F8BE-F2A2-3707-8754-436FBDB1DAF1> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/ATS
    0x7fff49873000 -     0x7fff49992fff  libFontParser.dylib (228.6) <BBCBEE2C-5B55-3278-B81D-22D72466753E> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontParser.dylib
    0x7fff49993000 -     0x7fff499deff7  libFontRegistry.dylib (228.12.1.1) <B515718C-81BC-3705-A207-7215486C6D28> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libFontRegistry.dylib
    0x7fff49a3d000 -     0x7fff49a70ff7  libTrueTypeScaler.dylib (228.6) <760BF895-3D7A-36E2-B97C-6775C3615A1D> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ATS.framework/Versions/A/Resources/libTrueTypeScaler.dylib
    0x7fff49ada000 -     0x7fff49adeff3  com.apple.ColorSyncLegacy (4.13.0 - 1) <4B1238CC-9B77-3AA5-8329-EE3C736F07EA> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/ColorSyncLegacy.framework/Versions/A/ColorSyncLegacy
    0x7fff49b7b000 -     0x7fff49bcdff3  com.apple.HIServices (1.22 - 627.14.2) <1F851BF9-AD29-3558-9EA5-AAD9BAAAC823> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/HIServices.framework/Versions/A/HIServices
    0x7fff49bce000 -     0x7fff49bdcff3  com.apple.LangAnalysis (1.7.0 - 1.7.0) <5654723A-7B3B-391F-B9F7-0DE4D5940185> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/LangAnalysis.framework/Versions/A/LangAnalysis
    0x7fff49bdd000 -     0x7fff49c29fff  com.apple.print.framework.PrintCore (14.2 - 503.8) <F1246C9A-2216-3390-8DF1-89304F47CE5D> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/PrintCore.framework/Versions/A/PrintCore
    0x7fff49c2a000 -     0x7fff49c65ff7  com.apple.QD (3.12 - 407.2) <F6B648DA-DA39-3EB4-B593-1B7E316661CD> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/QD.framework/Versions/A/QD
    0x7fff49c66000 -     0x7fff49c72ff7  com.apple.speech.synthesis.framework (8.1.0 - 8.1.0) <CF19C8B6-AAD5-3DCF-ABD0-3BABB44D119C> /System/Library/Frameworks/ApplicationServices.framework/Versions/A/Frameworks/SpeechSynthesis.framework/Versions/A/SpeechSynthesis
    0x7fff49c73000 -     0x7fff49f10fff  com.apple.audio.toolbox.AudioToolbox (1.14 - 1.14) <5D484151-F269-3D98-B507-0544A6B950AC> /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox
    0x7fff49f12000 -     0x7fff49f12fff  com.apple.audio.units.AudioUnit (1.14 - 1.14) <91100E0A-C14D-3E6C-B095-0C4109AC6694> /System/Library/Frameworks/AudioUnit.framework/Versions/A/AudioUnit
    0x7fff4a276000 -     0x7fff4a637fff  com.apple.CFNetwork (976 - 976) <A434842F-305B-301D-8F88-373CA7BF7196> /System/Library/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff4a64c000 -     0x7fff4a64cfff  com.apple.Carbon (158 - 158) <82E18DC5-6557-3A66-89A9-9FAD7B4E56DD> /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon
    0x7fff4a64d000 -     0x7fff4a650ffb  com.apple.CommonPanels (1.2.6 - 98) <775C94BE-EC00-315F-96E0-F0C1CD6EE3F4> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/CommonPanels.framework/Versions/A/CommonPanels
    0x7fff4a651000 -     0x7fff4a958ff7  com.apple.HIToolbox (2.1.1 - 917.3) <8FEBBC30-9C36-3AD4-BC4C-AE3537E8943D> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/HIToolbox
    0x7fff4a959000 -     0x7fff4a95cffb  com.apple.help (1.3.8 - 66) <0C6CC127-A860-30D2-8434-6CC3CAFFB030> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Help.framework/Versions/A/Help
    0x7fff4a95d000 -     0x7fff4a962ff7  com.apple.ImageCapture (9.0 - 1530.1) <72ABBF32-531B-3B04-926D-E14B8D9003A8> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/ImageCapture.framework/Versions/A/ImageCapture
    0x7fff4a963000 -     0x7fff4a9f7ff3  com.apple.ink.framework (10.9 - 225) <344AACCC-E997-3498-8B1D-2EFD3A889205> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Ink.framework/Versions/A/Ink
    0x7fff4a9f8000 -     0x7fff4aa12fff  com.apple.openscripting (1.7 - 179) <A57FC4DB-4C51-3ABB-842F-9578991043E3> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/OpenScripting.framework/Versions/A/OpenScripting
    0x7fff4aa33000 -     0x7fff4aa34fff  com.apple.print.framework.Print (14.2 - 267.4) <618D290C-2EA0-3959-A2A8-FB7B61DA92DD> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/Print.framework/Versions/A/Print
    0x7fff4aa35000 -     0x7fff4aa37ff7  com.apple.securityhi (9.0 - 55006) <2FE1EB07-F717-3E89-9662-8BA7C17C6AEC> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SecurityHI.framework/Versions/A/SecurityHI
    0x7fff4aa38000 -     0x7fff4aa3eff7  com.apple.speech.recognition.framework (6.0.3 - 6.0.3) <F7E95C56-19E8-30A1-9594-84D4DD89F6D4> /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/SpeechRecognition.framework/Versions/A/SpeechRecognition
    0x7fff4ab75000 -     0x7fff4ac41fff  com.apple.ColorSync (4.13.0 - 3340) <2F45EB01-0C51-3D25-9836-18F99222E1C7> /System/Library/Frameworks/ColorSync.framework/Versions/A/ColorSync
    0x7fff4addc000 -     0x7fff4ae6cfff  com.apple.audio.CoreAudio (4.3.0 - 4.3.0) <1E7EF105-B843-370D-884E-0A43E1A5800B> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
    0x7fff4aed2000 -     0x7fff4aefdff7  com.apple.CoreBluetooth (1.0 - 1) <F041753E-7709-3FA4-ADA3-6B37296D92FB> /System/Library/Frameworks/CoreBluetooth.framework/Versions/A/CoreBluetooth
    0x7fff4aefe000 -     0x7fff4b2acfff  com.apple.CoreData (120 - 866.1) <FD7900C2-5A00-3560-9F37-6EED4DDFE873> /System/Library/Frameworks/CoreData.framework/Versions/A/CoreData
    0x7fff4b2ad000 -     0x7fff4b396ff7  com.apple.CoreDisplay (101.3 - 106.2) <EE0D334B-8B71-3A70-9F90-677171D6762F> /System/Library/Frameworks/CoreDisplay.framework/Versions/A/CoreDisplay
    0x7fff4b397000 -     0x7fff4b7e5ff7  com.apple.CoreFoundation (6.9 - 1562) <DA75643F-6CF0-3FB1-B047-C142152E63B6> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff4b7e7000 -     0x7fff4be91ff7  com.apple.CoreGraphics (2.0 - 1249.2) <9F212010-3F68-33E7-AC96-716BD2BC90E4> /System/Library/Frameworks/CoreGraphics.framework/Versions/A/CoreGraphics
    0x7fff4be93000 -     0x7fff4c1bcfff  com.apple.CoreImage (14.2.0 - 720.0.130) <B356BA95-EDD3-35D8-9E4B-250AF6C6DDF9> /System/Library/Frameworks/CoreImage.framework/Versions/A/CoreImage
    0x7fff4c50d000 -     0x7fff4c60eff7  com.apple.CoreMedia (1.0 - 2285.4.4) <AC7E25F4-77B4-351E-974D-760F4F96FEDE> /System/Library/Frameworks/CoreMedia.framework/Versions/A/CoreMedia
    0x7fff4c672000 -     0x7fff4c672fff  com.apple.CoreServices (941 - 941) <6DBA4791-26DB-39FB-A6A3-5910A0F2EDD2> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices
    0x7fff4c673000 -     0x7fff4c6f1ffb  com.apple.AE (771 - 771) <4B009524-699E-3891-98DD-E3B6BB433C8F> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff4c6f2000 -     0x7fff4c9caff7  com.apple.CoreServices.CarbonCore (1178.16 - 1178.16) <17FC2B9E-EB6C-3768-A2D0-6E086F2563D9> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff4c9cb000 -     0x7fff4ca15ff7  com.apple.DictionaryServices (1.2 - 284.16.3) <1DAC9153-FB5A-3798-8797-CBFEFF227F71> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff4ca16000 -     0x7fff4ca1effb  com.apple.CoreServices.FSEvents (1239.200.12 - 1239.200.12) <8E1507EA-F0A8-3845-B32D-4FBC1381E89C> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/FSEvents.framework/Versions/A/FSEvents
    0x7fff4ca1f000 -     0x7fff4cbeafff  com.apple.LaunchServices (941 - 941) <A8E42760-995C-35E2-BF4A-C96FD0633B29> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff4cbeb000 -     0x7fff4cc8dfff  com.apple.Metadata (10.7.0 - 1191.53) <48609998-8A34-3CAF-8A42-52C180809656> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff4cc8e000 -     0x7fff4ccd9ff7  com.apple.CoreServices.OSServices (941 - 941) <1B9EA259-09DF-332B-807A-BD50F3184CAC> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff4ccda000 -     0x7fff4cd48ff7  com.apple.SearchKit (1.4.0 - 1.4.0) <CEC29BB5-D28E-3424-84FE-70756E521F3B> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff4cd49000 -     0x7fff4cd6dffb  com.apple.coreservices.SharedFileList (71.27 - 71.27) <6389B59D-DDAC-3C97-A982-137B9B1FB734> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList
    0x7fff4d0b5000 -     0x7fff4d21affb  com.apple.CoreText (352.0 - 584.26) <5F61037C-825D-37A4-9091-0047413CC213> /System/Library/Frameworks/CoreText.framework/Versions/A/CoreText
    0x7fff4d21b000 -     0x7fff4d258fff  com.apple.CoreVideo (1.8 - 0.0) <34EC73F1-F0ED-32F5-B96E-7683B1F9A7A2> /System/Library/Frameworks/CoreVideo.framework/Versions/A/CoreVideo
    0x7fff4d259000 -     0x7fff4d2efffb  com.apple.framework.CoreWLAN (13.0 - 1370.8) <32426190-3455-3049-8C09-0EC04D9C1279> /System/Library/Frameworks/CoreWLAN.framework/Versions/A/CoreWLAN
    0x7fff4d56c000 -     0x7fff4d571fff  com.apple.DiskArbitration (2.7 - 2.7) <97707A79-30E7-3D99-AA20-B992B0900BC4> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff4d73a000 -     0x7fff4db08fff  com.apple.Foundation (6.9 - 1562) <83D4A12B-EA5A-3C62-8D93-95E64F0A256B> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff4db79000 -     0x7fff4dba9ff3  com.apple.GSS (4.0 - 2.0) <86D07291-5DFC-30C2-9A18-5FCEDB0BE621> /System/Library/Frameworks/GSS.framework/Versions/A/GSS
    0x7fff4dcc3000 -     0x7fff4ddcdff3  com.apple.Bluetooth (6.0.10 - 6.0.10f1) <B3E7A841-1D1B-3043-A2C9-398928CB31AB> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth
    0x7fff4de2f000 -     0x7fff4dec2fff  com.apple.framework.IOKit (2.0.2 - 1483.240.1) <241690BB-8AFA-3B6A-A210-67874197CB59> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff4dec4000 -     0x7fff4deceff7  com.apple.IOSurface (255.1 - 255.1) <58826B1A-38E8-3C76-8FFC-76C9282DA893> /System/Library/Frameworks/IOSurface.framework/Versions/A/IOSurface
    0x7fff4df25000 -     0x7fff4e0c6ff7  com.apple.ImageIO.framework (3.3.0 - 1822.1) <1451559D-4224-3F53-A976-16CF186DDE80> /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
    0x7fff4e0c7000 -     0x7fff4e0cbffb  libGIF.dylib (1822.1) <9084A1A9-0AB3-314E-B76F-6642EAFD367A> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libGIF.dylib
    0x7fff4e0cc000 -     0x7fff4e1b1ff7  libJP2.dylib (1822.1) <8138A169-983C-3ACF-B05C-81317D8A3792> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJP2.dylib
    0x7fff4e1b2000 -     0x7fff4e1d7ffb  libJPEG.dylib (1822.1) <54E1BA95-B7C7-3078-921D-909B8EB33A84> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libJPEG.dylib
    0x7fff4e4ab000 -     0x7fff4e4d1ff3  libPng.dylib (1822.1) <5AFB0813-562F-3DB9-A4AD-A6FCABA63A2D> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libPng.dylib
    0x7fff4e4d2000 -     0x7fff4e4d4ff7  libRadiance.dylib (1822.1) <8CAA370A-A46C-3EA1-8338-F42AD183C19C> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libRadiance.dylib
    0x7fff4e4d5000 -     0x7fff4e522ffb  libTIFF.dylib (1822.1) <4748924B-8F25-30A9-95BF-0A106E908B36> /System/Library/Frameworks/ImageIO.framework/Versions/A/Resources/libTIFF.dylib
    0x7fff4f5cc000 -     0x7fff4f5e5fff  com.apple.Kerberos (3.0 - 1) <5D1B0593-3C0E-32D5-AAE5-ABC22A98B639> /System/Library/Frameworks/Kerberos.framework/Versions/A/Kerberos
    0x7fff4f8a3000 -     0x7fff4f8adfff  com.apple.MediaAccessibility (1.0 - 114.4) <C0584BAA-27BC-30F4-8B0C-5043559995AA> /System/Library/Frameworks/MediaAccessibility.framework/Versions/A/MediaAccessibility
    0x7fff4f967000 -     0x7fff50005fff  com.apple.MediaToolbox (1.0 - 2285.4.4) <BAA7289A-FD04-30AD-B46E-89310BF67C02> /System/Library/Frameworks/MediaToolbox.framework/Versions/A/MediaToolbox
    0x7fff50007000 -     0x7fff5009afff  com.apple.Metal (158.5 - 158.5) <72BF7187-81FE-389B-882F-7B2587FEB455> /System/Library/Frameworks/Metal.framework/Versions/A/Metal
    0x7fff500b7000 -     0x7fff500d7ff7  com.apple.MetalPerformanceShaders.MPSCore (1.0 - 1) <18281B14-0C6A-38F8-AB80-2D4BB0743C88> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSCore.framework/Versions/A/MPSCore
    0x7fff500d8000 -     0x7fff50156ff7  com.apple.MetalPerformanceShaders.MPSImage (1.0 - 1) <BEAF764B-362B-3C45-86F5-2AFBA5FA0F47> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSImage.framework/Versions/A/MPSImage
    0x7fff50157000 -     0x7fff5017ffff  com.apple.MetalPerformanceShaders.MPSMatrix (1.0 - 1) <116D6C1A-2FD7-3743-95A0-CDDA3D459529> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSMatrix.framework/Versions/A/MPSMatrix
    0x7fff50180000 -     0x7fff502b2ff7  com.apple.MetalPerformanceShaders.MPSNeuralNetwork (1.0 - 1) <88E80BEE-3D2B-328B-80D4-F4717BDB2E9F> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSNeuralNetwork.framework/Versions/A/MPSNeuralNetwork
    0x7fff502b3000 -     0x7fff502ceff7  com.apple.MetalPerformanceShaders.MPSRayIntersector (1.0 - 1) <E0E652B0-1624-3435-AD60-83A9C4B59852> /System/Library/Frameworks/MetalPerformanceShaders.framework/Frameworks/MPSRayIntersector.framework/Versions/A/MPSRayIntersector
    0x7fff502cf000 -     0x7fff502cfff7  com.apple.MetalPerformanceShaders.MetalPerformanceShaders (1.0 - 1) <1BBA8BC8-49C6-3C9B-B985-7CE4373E3553> /System/Library/Frameworks/MetalPerformanceShaders.framework/Versions/A/MetalPerformanceShaders
    0x7fff514cd000 -     0x7fff514d9ffb  com.apple.NetFS (6.0 - 4.0) <918DF6CD-2DB0-36A8-B869-5EF637A06C0D> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff53f90000 -     0x7fff53f98fe7  libcldcpuengine.dylib (2.10.3) <D7BF3AFE-3E48-35FF-B674-6CA33B982D63> /System/Library/Frameworks/OpenCL.framework/Versions/A/Libraries/libcldcpuengine.dylib
    0x7fff53f99000 -     0x7fff53ff1fff  com.apple.opencl (2.15.1 - 2.15.1) <CC9439C3-FF30-38D2-BF2F-EA0EF1B5775E> /System/Library/Frameworks/OpenCL.framework/Versions/A/OpenCL
    0x7fff53ff2000 -     0x7fff5400eff7  com.apple.CFOpenDirectory (10.14 - 207.200.4) <2CB1F122-2FA0-347C-8454-9CE0FA150832> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff5400f000 -     0x7fff5401bffb  com.apple.OpenDirectory (10.14 - 207.200.4) <A3FB0F0C-57F4-3F89-A4B1-63DA1F7C9E8E> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/OpenDirectory
    0x7fff5497e000 -     0x7fff54980fff  libCVMSPluginSupport.dylib (17.3.1) <B2310175-04D6-378B-A220-A8AD7F0DA68E> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCVMSPluginSupport.dylib
    0x7fff54981000 -     0x7fff54986ff3  libCoreFSCache.dylib (163.20) <566DB80E-F1D6-3AEC-AF06-08955507AFEE> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreFSCache.dylib
    0x7fff54987000 -     0x7fff5498bfff  libCoreVMClient.dylib (163.20) <B9A89373-BDCD-3003-9A82-6D73B930A122> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libCoreVMClient.dylib
    0x7fff5498c000 -     0x7fff54994ffb  libGFXShared.dylib (17.3.1) <9FFA679A-8CC9-3932-8A41-AA80C386AD3A> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGFXShared.dylib
    0x7fff54995000 -     0x7fff549a0fff  libGL.dylib (17.3.1) <CFAB6AE4-E646-3E8A-B872-EF091CAF949E> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGL.dylib
    0x7fff549a1000 -     0x7fff549dbfef  libGLImage.dylib (17.3.1) <1AEC8E56-D851-3516-96FE-2829883A8302> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLImage.dylib
    0x7fff549dc000 -     0x7fff54b4eff3  libGLProgrammability.dylib (17.3.1) <3B701B8D-FF2C-383E-8F94-77B052ECC075> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLProgrammability.dylib
    0x7fff54b4f000 -     0x7fff54b8cfff  libGLU.dylib (17.3.1) <90279918-D4B2-31E0-9709-8E06628D9486> /System/Library/Frameworks/OpenGL.framework/Versions/A/Libraries/libGLU.dylib
    0x7fff5553c000 -     0x7fff5554bff3  com.apple.opengl (17.3.1 - 17.3.1) <2F59064F-D6EF-35CD-9747-20A91DB3D5DF> /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL
    0x7fff5554c000 -     0x7fff556e2ff7  GLEngine (17.3.1) <2320D7E8-11EF-3667-8FC9-7EA5ABD6B8AD> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLEngine.bundle/GLEngine
    0x7fff556e3000 -     0x7fff5570bff7  GLRendererFloat (17.3.1) <444BAB14-2648-3CD9-863F-695EA9206059> /System/Library/Frameworks/OpenGL.framework/Versions/A/Resources/GLRendererFloat.bundle/GLRendererFloat
    0x7fff563a7000 -     0x7fff56600fff  com.apple.QuartzCore (1.11 - 696.3) <01A2F065-8759-311D-AC2E-FD49F52A87FA> /System/Library/Frameworks/QuartzCore.framework/Versions/A/QuartzCore
    0x7fff56e54000 -     0x7fff5717cff7  com.apple.security (7.0 - 58286.240.4) <91A03FF2-2EE9-36A7-AC4F-169E11FE7846> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff5717d000 -     0x7fff5720cfff  com.apple.securityfoundation (6.0 - 55185.200.14) <F6A0EC77-51DB-3312-991C-3E1F920DE8F1> /System/Library/Frameworks/SecurityFoundation.framework/Versions/A/SecurityFoundation
    0x7fff5723e000 -     0x7fff57242ff3  com.apple.xpc.ServiceManagement (1.0 - 1) <26BA237C-DBA0-3322-B9BF-8B8E739E3A20> /System/Library/Frameworks/ServiceManagement.framework/Versions/A/ServiceManagement
    0x7fff575ff000 -     0x7fff5766fff3  com.apple.SystemConfiguration (1.17 - 1.17) <A8FD596E-C858-397F-836C-978038B97AC0> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff578d0000 -     0x7fff57c32fff  com.apple.VideoToolbox (1.0 - 2285.4.4) <76B3A88C-9042-329D-8DD7-56AEE23D1790> /System/Library/Frameworks/VideoToolbox.framework/Versions/A/VideoToolbox
    0x7fff5a8dd000 -     0x7fff5a982fe7  com.apple.APFS (1.0 - 1) <BCB42C90-DEE0-3CD2-9B28-55CD8EFD9487> /System/Library/PrivateFrameworks/APFS.framework/Versions/A/APFS
    0x7fff5b3ce000 -     0x7fff5b3cfff3  com.apple.AggregateDictionary (1.0 - 1) <EBA6443E-6CF0-34F6-B77A-3FCEC57F8F80> /System/Library/PrivateFrameworks/AggregateDictionary.framework/Versions/A/AggregateDictionary
    0x7fff5b9cc000 -     0x7fff5b9f8ff7  com.apple.framework.Apple80211 (13.0 - 1376.2) <A71EADCB-7582-3D1B-9122-356F03E11594> /System/Library/PrivateFrameworks/Apple80211.framework/Versions/A/Apple80211
    0x7fff5bcd4000 -     0x7fff5bce3fcf  com.apple.AppleFSCompression (96.200.3 - 1.0) <78D538DD-1D24-34FC-AFB3-10411494870D> /System/Library/PrivateFrameworks/AppleFSCompression.framework/Versions/A/AppleFSCompression
    0x7fff5bde1000 -     0x7fff5bdecfff  com.apple.AppleIDAuthSupport (1.0 - 1) <E41452B2-3AFB-3493-BB82-0CE6D04DF424> /System/Library/PrivateFrameworks/AppleIDAuthSupport.framework/Versions/A/AppleIDAuthSupport
    0x7fff5be2d000 -     0x7fff5be76ff3  com.apple.AppleJPEG (1.0 - 1) <EC4C49F1-C060-3C0F-910F-3620985D4F12> /System/Library/PrivateFrameworks/AppleJPEG.framework/Versions/A/AppleJPEG
    0x7fff5c0c9000 -     0x7fff5c0f1ff7  com.apple.applesauce (1.0 - ???) <58654BC0-9243-39D1-BC43-B7F2E37A3A44> /System/Library/PrivateFrameworks/AppleSauce.framework/Versions/A/AppleSauce
    0x7fff5c1bc000 -     0x7fff5c20cfff  com.apple.AppleVAFramework (5.0.44 - 5.0.44) <618AB3FC-6A41-3A84-A305-CEA19434EB1C> /System/Library/PrivateFrameworks/AppleVA.framework/Versions/A/AppleVA
    0x7fff5c257000 -     0x7fff5c26dffb  com.apple.AssertionServices (1.0 - 1) <3F767D20-FE14-35CF-A089-E0445375ECFB> /System/Library/PrivateFrameworks/AssertionServices.framework/Versions/A/AssertionServices
    0x7fff5c5a9000 -     0x7fff5c84cff7  com.apple.AuthKit (1.0 - 1) <4FF8DA76-2250-39B9-B6A9-0E584C8B988F> /System/Library/PrivateFrameworks/AuthKit.framework/Versions/A/AuthKit
    0x7fff5ca1d000 -     0x7fff5ca26ff3  com.apple.coreservices.BackgroundTaskManagement (1.0 - 57.1) <05CF66F0-9650-3F75-9857-F8D186043866> /System/Library/PrivateFrameworks/BackgroundTaskManagement.framework/Versions/A/BackgroundTaskManagement
    0x7fff5ca27000 -     0x7fff5cac9fff  com.apple.backup.framework (1.10.3 - ???) <0B4C2292-AEA9-39B5-A65F-8F381166C5C2> /System/Library/PrivateFrameworks/Backup.framework/Versions/A/Backup
    0x7fff5caca000 -     0x7fff5cb3bffb  com.apple.BaseBoard (360.24 - 360.24) <04AF4372-C5D3-3F0A-A688-68D888D6D138> /System/Library/PrivateFrameworks/BaseBoard.framework/Versions/A/BaseBoard
    0x7fff5e6f0000 -     0x7fff5e6f9fff  com.apple.CommonAuth (4.0 - 2.0) <090893E5-BB65-39DA-A174-EAB2C7191EFE> /System/Library/PrivateFrameworks/CommonAuth.framework/Versions/A/CommonAuth
    0x7fff5ebb7000 -     0x7fff5ef8efef  com.apple.CoreAUC (273.0.0 - 273.0.0) <FE2B4D86-2C83-3FE2-A427-54DA2170E980> /System/Library/PrivateFrameworks/CoreAUC.framework/Versions/A/CoreAUC
    0x7fff5ef8f000 -     0x7fff5efc0fff  com.apple.CoreAVCHD (6.0.0 - 6000.4.1) <B15A24E4-2A92-3FD7-8F20-C372E4115FA7> /System/Library/PrivateFrameworks/CoreAVCHD.framework/Versions/A/CoreAVCHD
    0x7fff5f40a000 -     0x7fff5f41efff  com.apple.CoreEmoji (1.0 - 69.19.8) <26BC0F82-08C1-3EBD-9299-D3CC5091C467> /System/Library/PrivateFrameworks/CoreEmoji.framework/Versions/A/CoreEmoji
    0x7fff5f9f4000 -     0x7fff5fa66ff7  com.apple.CoreNLP (1.0 - 130.15.22) <D0A3E880-CDEA-360A-9838-220D76BAECC6> /System/Library/PrivateFrameworks/CoreNLP.framework/Versions/A/CoreNLP
    0x7fff5fd31000 -     0x7fff5fd39ffb  com.apple.CorePhoneNumbers (1.0 - 1) <2D9AF545-ED3C-3EC1-887F-86922652EC57> /System/Library/PrivateFrameworks/CorePhoneNumbers.framework/Versions/A/CorePhoneNumbers
    0x7fff5fec8000 -     0x7fff5fef9fff  com.apple.CoreServicesInternal (357 - 357) <789E57F4-5A14-3220-93DF-1D4FEE315431> /System/Library/PrivateFrameworks/CoreServicesInternal.framework/Versions/A/CoreServicesInternal
    0x7fff602ce000 -     0x7fff6035cff7  com.apple.CoreSymbolication (10.1 - 64460.6) <177AC44B-32E4-3F80-A36B-5B9999B388A8> /System/Library/PrivateFrameworks/CoreSymbolication.framework/Versions/A/CoreSymbolication
    0x7fff603ec000 -     0x7fff60518fff  com.apple.coreui (2.1 - 498.46) <5EFE2CDC-897C-3A6B-A60B-4E0FB1D1ECA9> /System/Library/PrivateFrameworks/CoreUI.framework/Versions/A/CoreUI
    0x7fff60519000 -     0x7fff6069efff  com.apple.CoreUtils (5.7.4 - 574.17) <DEF9C8A6-DDF1-37F4-A7F0-7DFAA95E8451> /System/Library/PrivateFrameworks/CoreUtils.framework/Versions/A/CoreUtils
    0x7fff606f5000 -     0x7fff60758ffb  com.apple.framework.CoreWiFi (13.0 - 1370.8) <818F8915-BA51-3145-9C40-C9B8D7BE2DBD> /System/Library/PrivateFrameworks/CoreWiFi.framework/Versions/A/CoreWiFi
    0x7fff60759000 -     0x7fff6076affb  com.apple.CrashReporterSupport (10.13 - 938.23) <D8D105F5-B6FB-3E91-A116-7CD92171E5C5> /System/Library/PrivateFrameworks/CrashReporterSupport.framework/Versions/A/CrashReporterSupport
    0x7fff607ed000 -     0x7fff607fcff3  com.apple.framework.DFRFoundation (1.0 - 211) <B72944ED-E4E8-3479-B832-8D50C4E30386> /System/Library/PrivateFrameworks/DFRFoundation.framework/Versions/A/DFRFoundation
    0x7fff607fd000 -     0x7fff60801ff7  com.apple.DSExternalDisplay (3.1 - 380) <76449D22-BA27-3FB1-AD25-A290936E6DEA> /System/Library/PrivateFrameworks/DSExternalDisplay.framework/Versions/A/DSExternalDisplay
    0x7fff60884000 -     0x7fff608fbffb  com.apple.datadetectorscore (7.0 - 590.24) <3A49EC90-2081-3031-8CAE-3A6D5F7BFA1E> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff60949000 -     0x7fff6098afff  com.apple.DebugSymbols (185 - 185) <64F5F9D6-401D-388B-82AD-A48B56413556> /System/Library/PrivateFrameworks/DebugSymbols.framework/Versions/A/DebugSymbols
    0x7fff6098b000 -     0x7fff60ae4ff7  com.apple.desktopservices (1.13.1 - ???) <AD61A660-0218-327E-8963-A1A170EC2C20> /System/Library/PrivateFrameworks/DesktopServicesPriv.framework/Versions/A/DesktopServicesPriv
    0x7fff61b26000 -     0x7fff61f4efff  com.apple.vision.FaceCore (3.3.4 - 3.3.4) <41218EB7-19C9-3813-A793-B0623387CADF> /System/Library/PrivateFrameworks/FaceCore.framework/Versions/A/FaceCore
    0x7fff65870000 -     0x7fff65871fff  libmetal_timestamp.dylib (902.2.2) <55E0B1F2-94F0-3A77-9DB3-152F44848DA5> /System/Library/PrivateFrameworks/GPUCompiler.framework/Versions/3902/Libraries/libmetal_timestamp.dylib
    0x7fff66f0f000 -     0x7fff66f1aff7  libGPUSupportMercury.dylib (17.3.1) <CBF68814-AF66-3B8D-AF60-69469EA92E61> /System/Library/PrivateFrameworks/GPUSupport.framework/Versions/A/Libraries/libGPUSupportMercury.dylib
    0x7fff66f1b000 -     0x7fff66f20ff7  com.apple.GPUWrangler (3.28.4 - 3.28.4) <7E06C75D-5502-3F1D-987C-4F103917CD85> /System/Library/PrivateFrameworks/GPUWrangler.framework/Versions/A/GPUWrangler
    0x7fff67d8b000 -     0x7fff67d9afff  com.apple.GraphVisualizer (1.0 - 5) <CAFE626E-9738-3C14-88AA-B6A9182F2C39> /System/Library/PrivateFrameworks/GraphVisualizer.framework/Versions/A/GraphVisualizer
    0x7fff67eeb000 -     0x7fff67f60fff  com.apple.Heimdal (4.0 - 2.0) <D99FF31F-6310-3D80-8AE3-64934385AC11> /System/Library/PrivateFrameworks/Heimdal.framework/Versions/A/Heimdal
    0x7fff69346000 -     0x7fff6934ffff  com.apple.IOAccelMemoryInfo (1.0 - 1) <4C91E3B6-3BB3-3AB6-942C-F67CC0B21228> /System/Library/PrivateFrameworks/IOAccelMemoryInfo.framework/Versions/A/IOAccelMemoryInfo
    0x7fff69350000 -     0x7fff69357ffb  com.apple.IOAccelerator (404.2.2 - 404.2.2) <2F099589-DBE9-3442-AC93-F4AB363482A0> /System/Library/PrivateFrameworks/IOAccelerator.framework/Versions/A/IOAccelerator
    0x7fff6935b000 -     0x7fff69374fff  com.apple.IOPresentment (1.0 - 42.6) <F7E91CC9-E4BB-3904-8647-0473E3BCAF70> /System/Library/PrivateFrameworks/IOPresentment.framework/Versions/A/IOPresentment
    0x7fff69789000 -     0x7fff697b8ff7  com.apple.IconServices (379 - 379) <694E17A6-471B-3C57-92D6-ECC4295FB859> /System/Library/PrivateFrameworks/IconServices.framework/Versions/A/IconServices
    0x7fff69a58000 -     0x7fff69a6bfff  com.apple.security.KeychainCircle.KeychainCircle (1.0 - 1) <DC6F5E18-3411-32AF-B395-AFC110C74A63> /System/Library/PrivateFrameworks/KeychainCircle.framework/Versions/A/KeychainCircle
    0x7fff69a87000 -     0x7fff69b7efff  com.apple.LanguageModeling (1.0 - 159.15.15) <34609F31-4DA1-3881-8947-85BEA7AFC938> /System/Library/PrivateFrameworks/LanguageModeling.framework/Versions/A/LanguageModeling
    0x7fff69b7f000 -     0x7fff69bc0ff7  com.apple.Lexicon-framework (1.0 - 33.15.10) <07E008F3-E823-333B-8B41-A46024AB0561> /System/Library/PrivateFrameworks/Lexicon.framework/Versions/A/Lexicon
    0x7fff69bc7000 -     0x7fff69bcdff7  com.apple.LinguisticData (1.0 - 238.23.4) <F6AA7095-3975-3C76-9833-BBE955EFEBD7> /System/Library/PrivateFrameworks/LinguisticData.framework/Versions/A/LinguisticData
    0x7fff6a42c000 -     0x7fff6a42ffff  com.apple.Mangrove (1.0 - 25) <8DF73279-BCEB-38CE-AE83-571C1B3FF45B> /System/Library/PrivateFrameworks/Mangrove.framework/Versions/A/Mangrove
    0x7fff6a92a000 -     0x7fff6a952ffb  com.apple.spotlight.metadata.utilities (1.0 - 1191.53) <2CFFD786-87A5-3629-B5E1-8E4DEF51ADA8> /System/Library/PrivateFrameworks/MetadataUtilities.framework/Versions/A/MetadataUtilities
    0x7fff6a953000 -     0x7fff6a9e5fff  com.apple.gpusw.MetalTools (1.0 - 1) <C0489BBD-C25C-33E5-84CD-8A50205080A0> /System/Library/PrivateFrameworks/MetalTools.framework/Versions/A/MetalTools
    0x7fff6a9fa000 -     0x7fff6aa13fff  com.apple.MobileAssets (1.0 - 437.230.2) <D962A68E-00AC-3C2F-BC09-0C16E77FE85E> /System/Library/PrivateFrameworks/MobileAsset.framework/Versions/A/MobileAsset
    0x7fff6ab90000 -     0x7fff6ababff3  com.apple.MobileKeyBag (2.0 - 1.0) <663E513E-CE91-3474-9108-77DF844F17BA> /System/Library/PrivateFrameworks/MobileKeyBag.framework/Versions/A/MobileKeyBag
    0x7fff6ac39000 -     0x7fff6ac63ff7  com.apple.MultitouchSupport.framework (2410.5 - 2410.5) <3A712911-F672-3BB3-B62B-A2A7BADF3578> /System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/A/MultitouchSupport
    0x7fff6aed6000 -     0x7fff6aee1fff  com.apple.NetAuth (6.2 - 6.2) <A6474ABC-FD4B-3A8F-AB33-7AACEEED7F0E> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff6b7ae000 -     0x7fff6b804fff  com.apple.OTSVG (1.0 - ???) <F020144A-D840-390D-A87F-29E8095C78AF> /System/Library/PrivateFrameworks/OTSVG.framework/Versions/A/OTSVG
    0x7fff6c96f000 -     0x7fff6c97eff3  com.apple.PerformanceAnalysis (1.217 - 217) <AA34989F-7E01-303E-8134-5BB37CE82DDF> /System/Library/PrivateFrameworks/PerformanceAnalysis.framework/Versions/A/PerformanceAnalysis
    0x7fff6e93d000 -     0x7fff6e95bff7  com.apple.ProtocolBuffer (1 - 263.1) <D70A1E3D-D2F7-3765-861C-173F5BBC848B> /System/Library/PrivateFrameworks/ProtocolBuffer.framework/Versions/A/ProtocolBuffer
    0x7fff6eb0a000 -     0x7fff6eb62f0f  com.apple.ROCKit (24 - 24) <FA6B086A-1841-3A5E-800B-CE7A52C3DAF1> /System/Library/PrivateFrameworks/ROCKit.framework/Versions/A/ROCKit
    0x7fff6ec86000 -     0x7fff6eca9ffb  com.apple.RemoteViewServices (2.0 - 128) <55D89BC9-0613-3910-B63E-9A146D35D91A> /System/Library/PrivateFrameworks/RemoteViewServices.framework/Versions/A/RemoteViewServices
    0x7fff7061f000 -     0x7fff7073dfff  com.apple.Sharing (1214.19 - 1214.19) <27C2CFC8-1C1B-3F98-B0BC-7AB6B1847B1B> /System/Library/PrivateFrameworks/Sharing.framework/Versions/A/Sharing
    0x7fff714f7000 -     0x7fff717a9ff3  com.apple.SkyLight (1.600.0 - 337.5) <B18B2F6F-F44B-3B5B-8DA1-3B8977E59240> /System/Library/PrivateFrameworks/SkyLight.framework/Versions/A/SkyLight
    0x7fff71f7a000 -     0x7fff71f87fff  com.apple.SpeechRecognitionCore (5.0.21 - 5.0.21) <FABB97BC-9555-33FE-B6C5-606CC403CE16> /System/Library/PrivateFrameworks/SpeechRecognitionCore.framework/Versions/A/SpeechRecognitionCore
    0x7fff7266c000 -     0x7fff726abff3  com.apple.StreamingZip (1.0 - 1) <251128E7-C343-3799-A31B-8B10CEC69F19> /System/Library/PrivateFrameworks/StreamingZip.framework/Versions/A/StreamingZip
    0x7fff72de8000 -     0x7fff72e75ff7  com.apple.Symbolication (10.1 - 64460.8) <7DDC5C90-947F-34FF-864D-5ED3C2B746A9> /System/Library/PrivateFrameworks/Symbolication.framework/Versions/A/Symbolication
    0x7fff7337e000 -     0x7fff7338bffb  com.apple.TCC (1.0 - 1) <81F88B91-49C1-36E7-8A39-C4BD654EE942> /System/Library/PrivateFrameworks/TCC.framework/Versions/A/TCC
    0x7fff735fe000 -     0x7fff736c5ff7  com.apple.TextureIO (3.8.4 - 3.8.1) <83CDF659-E5B3-381F-BDA1-FF0BFA17B5EE> /System/Library/PrivateFrameworks/TextureIO.framework/Versions/A/TextureIO
    0x7fff7377f000 -     0x7fff73780fff  com.apple.TrustEvaluationAgent (2.0 - 31.200.1) <5C3E1B2D-40A8-3237-A8D9-4E7B15EEA678> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff73786000 -     0x7fff73940fff  com.apple.UIFoundation (1.0 - 551) <65A80450-7A24-3366-B521-4D02C4DB5094> /System/Library/PrivateFrameworks/UIFoundation.framework/Versions/A/UIFoundation
    0x7fff7462f000 -     0x7fff74718ff7  com.apple.ViewBridge (401.1 - 401.1) <E76BC854-5B08-3FFF-AA2C-9679754FCAF0> /System/Library/PrivateFrameworks/ViewBridge.framework/Versions/A/ViewBridge
    0x7fff74f3e000 -     0x7fff74f41fff  com.apple.dt.XCTTargetBootstrap (1.0 - 1) <5F779D77-4AB1-3CCD-9AAF-101EC7E4905B> /System/Library/PrivateFrameworks/XCTTargetBootstrap.framework/Versions/A/XCTTargetBootstrap
    0x7fff75372000 -     0x7fff75374ff3  com.apple.loginsupport (1.0 - 1) <67BC49D6-320F-33ED-912E-16E5A342F385> /System/Library/PrivateFrameworks/login.framework/Versions/A/Frameworks/loginsupport.framework/Versions/A/loginsupport
    0x7fff75375000 -     0x7fff7538afff  com.apple.login (3.0 - 3.0) <D6486C5A-E644-3F43-AD27-5E14685CD8D6> /System/Library/PrivateFrameworks/login.framework/Versions/A/login
    0x7fff7562f000 -     0x7fff75667fff  libCRFSuite.dylib (41.15.4) <92752A96-D1CF-3CA1-837A-1E075AE4C642> /usr/lib/libCRFSuite.dylib
    0x7fff7566a000 -     0x7fff75675ff7  libChineseTokenizer.dylib (28.15.3) <55572692-4918-3C54-AD35-726E03EC47D5> /usr/lib/libChineseTokenizer.dylib
    0x7fff75706000 -     0x7fff75707ff7  libDiagnosticMessagesClient.dylib (107) <15210AC0-61F9-3F9D-A159-A009F62EB537> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff7573e000 -     0x7fff75901ff7  libFosl_dynamic.dylib (18.3.2) <D67B74E9-EB95-38BC-995C-5F4CC044C3F7> /usr/lib/libFosl_dynamic.dylib
    0x7fff75957000 -     0x7fff75976ff7  libMobileGestalt.dylib (645.220.9) <C2C55511-993B-34D2-9040-902BFDA38141> /usr/lib/libMobileGestalt.dylib
    0x7fff75977000 -     0x7fff75977fff  libOpenScriptingUtil.dylib (179) <441A2E60-5D5C-3567-9B00-AA22E6EE5358> /usr/lib/libOpenScriptingUtil.dylib
    0x7fff75ab8000 -     0x7fff75ab9ffb  libSystem.B.dylib (1252.200.5) <C6201660-5E17-397D-BA21-C503420CD706> /usr/lib/libSystem.B.dylib
    0x7fff75b43000 -     0x7fff75b44fff  libThaiTokenizer.dylib (2.15.1) <F09EB0BB-1E8A-3391-BEF5-7D91F0715A62> /usr/lib/libThaiTokenizer.dylib
    0x7fff75b57000 -     0x7fff75b6dffb  libapple_nghttp2.dylib (1.24.1) <71C126C5-D869-3E67-9778-058FA7F3CA74> /usr/lib/libapple_nghttp2.dylib
    0x7fff75b6e000 -     0x7fff75b97ffb  libarchive.2.dylib (54.200.3) <32B8634D-E465-3F6D-B254-A20D44504508> /usr/lib/libarchive.2.dylib
    0x7fff75b98000 -     0x7fff75c97ff7  libate.dylib (1.13.8) <6FF4C626-689E-3464-B2C5-C01F3C084219> /usr/lib/libate.dylib
    0x7fff75c9b000 -     0x7fff75c9bff3  libauto.dylib (187) <003DEF68-0C59-3AFB-A7B7-A1B5ED301AF2> /usr/lib/libauto.dylib
    0x7fff75d72000 -     0x7fff75d82ff3  libbsm.0.dylib (39.200.18) <58A9ACEC-BF46-3A4E-86F5-3DD9AD7095B4> /usr/lib/libbsm.0.dylib
    0x7fff75d83000 -     0x7fff75d91fff  libbz2.1.0.dylib (38.200.3) <4DEC3797-087F-3C8D-815B-48E895813251> /usr/lib/libbz2.1.0.dylib
    0x7fff75d92000 -     0x7fff75de9ff7  libc++.1.dylib (400.9.4) <B260AC33-EB9A-30C6-8746-D011B3B02B08> /usr/lib/libc++.1.dylib
    0x7fff75dea000 -     0x7fff75dfffff  libc++abi.dylib (400.17) <446F4748-8A89-3D2E-AE1C-27EEBE93A8AB> /usr/lib/libc++abi.dylib
    0x7fff75e00000 -     0x7fff75e00ff3  libcharset.1.dylib (51.200.6) <43F7E100-F5D1-36AB-A26E-CF94196A19C0> /usr/lib/libcharset.1.dylib
    0x7fff75e01000 -     0x7fff75e11ffb  libcmph.dylib (6.15.1) <CEDA6538-C071-3B5A-948E-DF61E2878983> /usr/lib/libcmph.dylib
    0x7fff75e12000 -     0x7fff75e2afdb  libcompression.dylib (52.200.13) <6298529A-0120-3360-891C-84436972EA8D> /usr/lib/libcompression.dylib
    0x7fff760d5000 -     0x7fff760ebfff  libcoretls.dylib (155.220.1) <1229F9EA-C070-3D03-9DC6-F548C59F9FD5> /usr/lib/libcoretls.dylib
    0x7fff760ec000 -     0x7fff760edff3  libcoretls_cfhelpers.dylib (155.220.1) <33661841-3C3B-3608-86AC-C88D1CD6FE98> /usr/lib/libcoretls_cfhelpers.dylib
    0x7fff7628c000 -     0x7fff7641cffb  libcrypto.35.dylib (22.240.1) <603427B4-6A5E-367B-B164-744606A2AA27> /usr/lib/libcrypto.35.dylib
    0x7fff76764000 -     0x7fff767bbffb  libcups.2.dylib (462.10) <29B6D106-A5F2-321D-8916-90F595545D88> /usr/lib/libcups.2.dylib
    0x7fff768f3000 -     0x7fff768f3fff  libenergytrace.dylib (17.200.1) <F5BA8134-16F9-31CD-90E1-D1EBEBADA4AE> /usr/lib/libenergytrace.dylib
    0x7fff76925000 -     0x7fff7692aff7  libgermantok.dylib (17.15.2) <9381B152-5CFD-3D23-A5A7-4D64EE55B85E> /usr/lib/libgermantok.dylib
    0x7fff7692b000 -     0x7fff76930ff7  libheimdal-asn1.dylib (520.220.2) <D851A47D-E162-35F8-B8D4-6ABEA7FFDAD7> /usr/lib/libheimdal-asn1.dylib
    0x7fff7695c000 -     0x7fff76a4dff7  libiconv.2.dylib (51.200.6) <9FB95807-7C62-32B7-A19F-946D7FB7CCA6> /usr/lib/libiconv.2.dylib
    0x7fff76a4e000 -     0x7fff76cb1ffb  libicucore.A.dylib (62109.0.1) <FEB89BD3-79C4-3208-A754-7E6BC4D38548> /usr/lib/libicucore.A.dylib
    0x7fff76cfe000 -     0x7fff76cfffff  liblangid.dylib (128.15.1) <663D0A24-7260-31D1-9BFE-74D67B6F72F6> /usr/lib/liblangid.dylib
    0x7fff76d00000 -     0x7fff76d18fff  liblzma.5.dylib (10.200.3) <9A52A949-0CB1-39B6-9244-D079FB609559> /usr/lib/liblzma.5.dylib
    0x7fff76d30000 -     0x7fff76de0fff  libmecab.1.0.0.dylib (779.24.1) <590BC39C-2A3E-368B-9499-C808B84C4955> /usr/lib/libmecab.1.0.0.dylib
    0x7fff76de1000 -     0x7fff7701eff7  libmecabra.dylib (779.24.1) <22BFD5A8-EA42-3DC3-8910-F27DCFB1B631> /usr/lib/libmecabra.dylib
    0x7fff771f6000 -     0x7fff7754effb  libnetwork.dylib (1229.240.1) <F99593DA-3089-3008-BE5B-5AC096EBF3A3> /usr/lib/libnetwork.dylib
    0x7fff775e0000 -     0x7fff77d69fd7  libobjc.A.dylib (750.1) <4D6C889C-60F4-3028-9B13-DD3DFE6A2A44> /usr/lib/libobjc.A.dylib
    0x7fff77d7c000 -     0x7fff77d80ffb  libpam.2.dylib (22.200.1) <85253002-89F2-3872-9C8A-1801303A2EBB> /usr/lib/libpam.2.dylib
    0x7fff77d83000 -     0x7fff77db9ff7  libpcap.A.dylib (79.200.4) <6D25197A-2F7C-3147-A45A-F6F13E55909F> /usr/lib/libpcap.A.dylib
    0x7fff77ed3000 -     0x7fff77eebffb  libresolv.9.dylib (65.200.2) <A1A77B4E-1AF0-3039-9945-D05440494E00> /usr/lib/libresolv.9.dylib
    0x7fff77f3d000 -     0x7fff77f3eff7  libspindump.dylib (267.1) <9DEA015B-410E-3D6E-A3EE-54E046092EA9> /usr/lib/libspindump.dylib
    0x7fff77f3f000 -     0x7fff7810bff7  libsqlite3.dylib (274.22) <B33F9DBF-5947-31B4-A61C-EBB5326C6CD3> /usr/lib/libsqlite3.dylib
    0x7fff78398000 -     0x7fff7839bffb  libutil.dylib (51.200.4) <10C5E165-0939-363A-9D13-7076F3B513EC> /usr/lib/libutil.dylib
    0x7fff7839c000 -     0x7fff783a9fff  libxar.1.dylib (404) <16E875B3-CF89-3059-87BB-36D301B32E7B> /usr/lib/libxar.1.dylib
    0x7fff783ae000 -     0x7fff78491fff  libxml2.2.dylib (32.8) <3E7875AC-3195-3800-AC48-8AA3B7BE51E4> /usr/lib/libxml2.2.dylib
    0x7fff78492000 -     0x7fff784baff3  libxslt.1.dylib (16.1) <D6EBFEBB-F88E-398F-B1B5-66F413C2CD32> /usr/lib/libxslt.1.dylib
    0x7fff784bb000 -     0x7fff784cdffb  libz.1.dylib (70.200.4) <15F7B40A-424C-33BB-BF2C-7E8195128B78> /usr/lib/libz.1.dylib
    0x7fff7853e000 -     0x7fff78542ff3  libcache.dylib (81) <704331AC-E43D-343A-8C24-39201142AF27> /usr/lib/system/libcache.dylib
    0x7fff78543000 -     0x7fff7854dff3  libcommonCrypto.dylib (60118.220.1) <9C865644-EE9A-3662-AB77-7C8A5E561784> /usr/lib/system/libcommonCrypto.dylib
    0x7fff7854e000 -     0x7fff78555fff  libcompiler_rt.dylib (63.4) <817772E3-E836-3FFD-A39B-BDCD1C357221> /usr/lib/system/libcompiler_rt.dylib
    0x7fff78556000 -     0x7fff7855fff3  libcopyfile.dylib (146.200.3) <5C5C4F35-DAB7-3CF1-940F-F47192AB8289> /usr/lib/system/libcopyfile.dylib
    0x7fff78560000 -     0x7fff785e4fdf  libcorecrypto.dylib (602.230.1) <C78D1A87-5543-3561-BEB4-3B480BA94ECB> /usr/lib/system/libcorecrypto.dylib
    0x7fff7866b000 -     0x7fff786a5ff7  libdispatch.dylib (1008.220.2) <2FDB1401-5119-3DF0-91F5-F4E105F00CD7> /usr/lib/system/libdispatch.dylib
    0x7fff786a6000 -     0x7fff786d5ff3  libdyld.dylib (655.1) <90C801E7-5D05-37A8-810C-B58E8C53953A> /usr/lib/system/libdyld.dylib
    0x7fff786d6000 -     0x7fff786d6ffb  libkeymgr.dylib (30) <A4EFD9A4-2EF3-3E18-B325-F527E3821939> /usr/lib/system/libkeymgr.dylib
    0x7fff786d7000 -     0x7fff786e3ff7  libkxld.dylib (4903.241.1) <D039B38D-E8E6-3011-94F5-A21CD3D59526> /usr/lib/system/libkxld.dylib
    0x7fff786e4000 -     0x7fff786e4ff7  liblaunch.dylib (1336.240.2) <D5F0014D-CF46-3B04-9DE0-A1466DA14A2C> /usr/lib/system/liblaunch.dylib
    0x7fff786e5000 -     0x7fff786eafff  libmacho.dylib (921) <6ADB99F3-D142-3A0A-B3CE-031354766ACC> /usr/lib/system/libmacho.dylib
    0x7fff786eb000 -     0x7fff786edffb  libquarantine.dylib (86.220.1) <58524FD7-63C5-38E0-9D90-845A79551C14> /usr/lib/system/libquarantine.dylib
    0x7fff786ee000 -     0x7fff786efff3  libremovefile.dylib (45.200.2) <BA53CA8A-9974-3A43-9265-B110B1AE470F> /usr/lib/system/libremovefile.dylib
    0x7fff786f0000 -     0x7fff78707ff3  libsystem_asl.dylib (356.200.4) <33C62769-1242-3BC1-9459-13CBCDECC7FE> /usr/lib/system/libsystem_asl.dylib
    0x7fff78708000 -     0x7fff78708fff  libsystem_blocks.dylib (73) <152EDADF-7D94-35F2-89B7-E66DCD945BBA> /usr/lib/system/libsystem_blocks.dylib
    0x7fff78709000 -     0x7fff78791fff  libsystem_c.dylib (1272.200.26) <D6C701A2-9F17-308D-B6AC-9E17EF31B7DF> /usr/lib/system/libsystem_c.dylib
    0x7fff78792000 -     0x7fff78795ff7  libsystem_configuration.dylib (963.200.27) <94898525-ECC8-3CC9-B312-CBEAAC305E32> /usr/lib/system/libsystem_configuration.dylib
    0x7fff78796000 -     0x7fff78799ff7  libsystem_coreservices.dylib (66) <10818C17-70E1-328E-A3E3-C3EB81AEC590> /usr/lib/system/libsystem_coreservices.dylib
    0x7fff7879a000 -     0x7fff787a0ffb  libsystem_darwin.dylib (1272.200.26) <07468CF7-982F-37C4-83D0-D5E602A683AA> /usr/lib/system/libsystem_darwin.dylib
    0x7fff787a1000 -     0x7fff787a7ff7  libsystem_dnssd.dylib (878.240.1) <5FEA5E1E-E80F-3616-AD33-8E936D61F31A> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff787a8000 -     0x7fff787f4ff3  libsystem_info.dylib (517.200.9) <54B65F21-2E93-3579-9B72-6637A03245D9> /usr/lib/system/libsystem_info.dylib
    0x7fff787f5000 -     0x7fff7881dff7  libsystem_kernel.dylib (4903.241.1) <CA10BC3A-5B09-32CE-B74F-BAD01755AA37> /usr/lib/system/libsystem_kernel.dylib
    0x7fff7881e000 -     0x7fff78869ff7  libsystem_m.dylib (3158.200.7) <AF25F8E8-194C-314F-A2D3-A424853EE796> /usr/lib/system/libsystem_m.dylib
    0x7fff7886a000 -     0x7fff7888eff7  libsystem_malloc.dylib (166.220.1) <4777DC06-F9C6-356E-82AB-86A1C6D62F3A> /usr/lib/system/libsystem_malloc.dylib
    0x7fff7888f000 -     0x7fff7889aff3  libsystem_networkextension.dylib (767.240.1) <4DB0D4A2-83E7-3638-AAA0-39CECD5C25F8> /usr/lib/system/libsystem_networkextension.dylib
    0x7fff7889b000 -     0x7fff788a2fff  libsystem_notify.dylib (172.200.21) <65B3061D-41D7-3485-B217-A861E05AD50B> /usr/lib/system/libsystem_notify.dylib
    0x7fff788a3000 -     0x7fff788acfef  libsystem_platform.dylib (177.200.16) <83DED753-51EC-3B8C-A98D-883A5184086B> /usr/lib/system/libsystem_platform.dylib
    0x7fff788ad000 -     0x7fff788b7fff  libsystem_pthread.dylib (330.230.1) <80CC5992-823E-327E-BB6E-9D4568B84161> /usr/lib/system/libsystem_pthread.dylib
    0x7fff788b8000 -     0x7fff788bbff7  libsystem_sandbox.dylib (851.230.3) <D6469A17-C13C-3538-A300-D6517BB7F249> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff788bc000 -     0x7fff788beff3  libsystem_secinit.dylib (30.220.1) <5964B6D2-19D4-3CF9-BDBC-4EB1D42348F1> /usr/lib/system/libsystem_secinit.dylib
    0x7fff788bf000 -     0x7fff788c6ff7  libsystem_symptoms.dylib (820.237.2) <487E1794-4C6E-3B1B-9C55-95B1A5FF9B90> /usr/lib/system/libsystem_symptoms.dylib
    0x7fff788c7000 -     0x7fff788dcff7  libsystem_trace.dylib (906.220.1) <4D4BA88A-FA32-379D-8860-33838723B35F> /usr/lib/system/libsystem_trace.dylib
    0x7fff788de000 -     0x7fff788e3ffb  libunwind.dylib (35.4) <EF1A77FD-A86B-39F5-ABEA-6100AB23583A> /usr/lib/system/libunwind.dylib
    0x7fff788e4000 -     0x7fff78914fff  libxpc.dylib (1336.240.2) <EE0CDA53-6FF9-3B4E-A571-335A5FF6B6F4> /usr/lib/system/libxpc.dylib

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 2
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 47726024
    thread_create: 1
    thread_set_state: 7047

VM Region Summary:
ReadOnly portion of Libraries: Total=434.7M resident=0K(0%) swapped_out_or_unallocated=434.7M(100%)
Writable regions: Total=689.4M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=689.4M(100%)
 
                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Accelerate framework               128K        2 
Activity Tracing                   256K        2 
CG backing stores                 2232K        5 
CG image                           108K       10 
CoreAnimation                       40K        8 
CoreGraphics                         8K        2 
CoreImage                           12K        4 
CoreUI image data                  388K       10 
CoreUI image file                  436K        6 
Foundation                           4K        2 
Image IO                            68K        2 
JS JIT generated code               40K        7 
JS VM register file               6400K        6 
Kernel Alloc Once                    8K        2 
MALLOC                           277.8M       43 
MALLOC guard page                   32K        8 
MALLOC_NANO (reserved)           384.0M        2         reserved VM address space (unallocated)
Memory Tag 242                      12K        2 
OpenGL GLSL                        256K        4 
STACK GUARD                       56.0M       12 
Stack                             13.1M       14 
VM_ALLOCATE                        484K       23 
WebAssembly memory                4096K        2 
__DATA                            35.8M      301 
__FONT_DATA                          4K        2 
__GLSLBUILTINS                    5176K        2 
__LINKEDIT                       222.1M       38 
__TEXT                           212.7M      293 
__UNICODE                          564K        2 
mapped file                      417.9M       34 
shared memory                     1636K       14 
===========                     =======  ======= 
TOTAL                              1.6G      833 
TOTAL, minus reserved VM space     1.2G      833 

Model: MacPro5,1, BootROM 140.0.0.0.0, 6 processors, 6-Core Intel Xeon, 3.33 GHz, 32 GB, SMC 1.39f11
Graphics: Radeon RX 560, Radeon RX 560, PCIe
Memory Module: DIMM 1, 8 GB, DDR3 ECC, 1333 MHz, 0x8543, 0x44332D36304D4D31303453562D3939390000
Memory Module: DIMM 2, 8 GB, DDR3 ECC, 1333 MHz, 0x8543, 0x44332D36304D4D31303453562D3939390000
Memory Module: DIMM 3, 8 GB, DDR3 ECC, 1333 MHz, 0x8543, 0x44332D36304D4D31303453562D3939390000
Memory Module: DIMM 4, 8 GB, DDR3 ECC, 1333 MHz, 0x8543, 0x44332D36304D4D31303453562D3939390000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x8E), Broadcom BCM43xx 1.0 (5.106.98.102.30)
Bluetooth: Version 6.0.10f1, 3 services, 27 devices, 1 incoming serial ports
Network Service: Ethernet 1, Ethernet, en0
PCI Card: Radeon RX 560, Display Controller, Slot-1
PCI Card: pci1002,aae0, Audio Device, Slot-1
Serial ATA Device: HL-DT-ST DVD-RW GH61N
Serial ATA Device: ST1000DM003-1CH162, 1 TB
Serial ATA Device: WDC WD20EADS-00S2B0, 2 TB
Serial ATA Device: ST3000DM008-2DM166, 3 TB
Serial ATA Device: Crucial_CT525MX300SSD1, 525.11 GB
USB Device: USB Bus
USB Device: USB Bus
USB Device: USB Bus
USB Device: BRCM2046 Hub
USB Device: Bluetooth USB Host Controller
USB Device: USB Bus
USB Device: AirPod Case
USB Device: USB Bus
USB Device: USB Bus
USB Device: USB 2.0 Bus
USB Device: USB 2.0 Bus
USB Device: HL-L2395DW series
USB Device: Keyboard Hub
USB Device: Apple Keyboard
FireWire Device: built-in_hub, Up to 800 Mb/sec
Thunderbolt Bus: 
```

### Version information

- **Quaternion version**: 0.0.9.4-beta1
- **Install method**: .dmg
- **Platform**: macOS 10.14.3

### PR DESCRIPTION
**Pull request by krkk**
Closes #521

### CODE REVIEW

**Comment by aaronraimist** [comment]
Instead of checking if there is no room, would it be better to check if there are no users? I mean theoretically every room should have a user but

**Comment by krkk** [comment]
Searching users in empty room should work fine. The crash is caused by calling a function of uninitialised object which gets the list of users

**Comment by KitsuneRal** [comment]
While this check certainly should be merged, I'd be happy to see enabling/disabling the search input box in `UserListModel::setRoom()` - and start the application with the control disabled, of course. A failproof is great but a visual cue to the user is even better.

File: client/userlistdock.h [hunk 1]
```diff
@@ -21,6 +21,7 @@
 
 #include <QtWidgets/QVBoxLayout>
 #include <QtWidgets/QDockWidget>
+#include <QtWidgets/QLineEdit>
```
Comment (KitsuneRal) [inline client/userlistdock.h]: You can just use `class QLineEdit;`, similar to `QTableView` and `QMenu`, below.
